### ISSUE TITLE
BMElib test matlab vs python vs R

### ISSUE THREAD

**Issue by ivanhanigan** [swish-climate-impact-assessment/AirPollutionNeighbourhoodExposures#1]
- the matlab install is on UCRH servers
- worth testing http://sourceforge.net/projects/bmelibpy/ and http://bmelibpy.sourceforge.net/

**Comment by ivanhanigan** [comment]
@ozjimbob this is a test of the email feature in github

**Comment by ivanhanigan** [comment]
hi @ozjimbob I have uploaded the latest workflow visualisation to this site.  can you confirm you get these email notifications?  cheers

**Comment by ivanhanigan** [comment]
- We need to configure the installed BMElib matlab.  Should we also test the python vs matlab?
- It would be great if we did not have to rely on the Matlab tool and could just use the python, or even R kriging tools
- it looks like a standard krige (but the data points are  'residuals' from the prior)
- we think we just feed in hard points 'X with no error' and soft  points 'J with error_j'
- we looked at the R krige function (gstat::krige) it says we can input weights
  as 1/variance so we think we can add X (error_x = 1) and J (error_j)
- does this sound like we are using the right terms and concepts?

**Comment by ivanhanigan** [comment]
Perhaps you get notifications if you are a collaborator @ozjimbob ?

**Comment by ivanhanigan** [comment]
Testing @ivanhanigan

**Comment by ozjimbob** [comment]
Testing @ivanhanigan

**Comment by ozjimbob** [comment]
Hi @ivanhanigan try going to settings -> notification centre and turing on email for @ replies
@ozjimbob

**Comment by ivanhanigan** [comment]
Yep that came thru my gmail

**Comment by ivanhanigan** [comment]
Hey that exact option not in me settings notify centr @ozjimbob

**Comment by ivanhanigan** [comment]
I wonder if you get emails to yourself? @ivanhanigan

**Comment by ivanhanigan** [comment]
I am going to start a manuscript for this today @ivanhanigan

**Comment by ivanhanigan** [comment]
Looks like the python port has been abandoned.  Closed
